### ISSUE TITLE
version EN

### ISSUE THREAD

**Issue by jeanlouislcdw** [blendwebmix/blendwebmix2018#1]
Hello, j'ai modifié le texte de la "HomePage" (http://2018.blendwebmix.com/en/) en back mais le front reste vide
Pourquoi tant de haine ?

**Comment by votredsi** [comment]
Parce que tu es en anglais ?

[image: photo]
*Sylvain FAVRE*
Votre DSI
+33.6.46.67.15.89 | s.favre@votre-dsi.fr | http://www.votre-dsi.fr | 17 rue
du Berry
<http://www.facebook.com/VotreDsi>  <http://fr.linkedin.com/in/sfavre>
<http://twitter.com/votre_dsi>

2018-04-04 15:42 GMT+02:00 jeanlouislcdw <notifications@github.com>:

**Comment by jeanlouislcdw** [comment]
pardon ? non je ne crois pas
Moi je vais là http://2018.blendwebmix.com/wp-admin/post.php?post=182&action=edit, je saisi du texte et il ne s'affiche nulle part 
Ou pour le dire autrement quand je vais sur la page http://2018.blendwebmix.com/en/ que je clique sur "Edit page" et que je rajoute du contenu, il est bien "mémorisé" en back mais pas affiché en front

**Comment by truchot** [comment]
Il était pas dans la bonne langue et pas assigner avec la page d'accueil FR donc WordPress ne faisait pas le lien c'est corrigé ;)
